require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.4'

target 'UEH' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'RNCCheckbox', :path => '../node_modules/@react-native-community/checkbox'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'


  use_flipper!({ 'Flipper-Folly' => '2.5' }) # update this part
 post_install do |installer|
   flipper_post_install(installer)

   installer.pods_project.targets.each do |target|
    if target.name == "React-Core-AccessibilityResources"
      target.remove_from_project
    end
  end

 end
end


pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
