require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.4'

target 'UEH' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'RNCCheckbox', :path => '../node_modules/@react-native-community/checkbox'


  pod 'YogaKit', '~> 1.7'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'UEHTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.

  use_flipper!({ 'Flipper-Folly' => '2.3.0' }) # update this part
 post_install do |installer|
   flipper_post_install(installer)
 end
end

target 'UEH-tvOS' do
  # Pods for UEH-tvOS

  target 'UEH-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
